package works.resolve.pathfinder.ai.api

import works.resolve.pathfinder.ai.utils.shortHash
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Unit tests for the Mistral payload helpers, pinning parity with pi's
 * shortHash, deriveMistralToolCallId, the tool-call ID normalizer, and
 * buildToolResultText. Expected hash values were generated by running pi's
 * src/utils/hash.ts under node.
 */
class MistralConversationsPayloadTest {

    @Test
    fun `shortHash matches pi reference values`() {
        // Values produced by pi's shortHash (UTF-16 code-unit iteration).
        assertEquals("k4n83c7h0j2b", shortHash(""))
        assertEquals("y0biex7f9bbh", shortHash("abc"))
        assertEquals("1nlso9v7di2pi", shortHash("toolcall:0"))
        assertEquals("1h9muox1to064d", shortHash("openai-response-id-with-pipes|and-stuff-450-chars"))
        assertEquals("ih6tp613o7wt8", shortHash("héllo 🌍"))
        assertEquals("144a7j62ld7en", shortHash("abc:1"))
    }

    @Test
    fun `deriveMistralToolCallId keeps 9-char alnum ids and hashes the rest`() {
        assertEquals("abc123456", deriveMistralToolCallId("abc123456", 0))
        assertEquals("abc123456", deriveMistralToolCallId("abc-123_456", 0))
        val derived = deriveMistralToolCallId("toolcall:0", 0)
        // "toolcall:0" strips to the 9-char "toolcall0", returned as-is (pi parity).
        assertEquals("toolcall0", derived)
        // Reference value from pi's deriveMistralToolCallId under node.
        assertEquals("knulnuw1n", deriveMistralToolCallId("toolcall:00", 0))
        // Empty normalized ids hash the raw string as seed.
        assertEquals(shortHash("---").take(9), deriveMistralToolCallId("---", 0))
        // Later attempts append a discriminator to the seed.
        assertEquals(shortHash("abc:1").take(9), deriveMistralToolCallId("abc", 1))
    }

    @Test
    fun `normalizer is stable and avoids collisions`() {
        val normalizer = MistralToolCallIdNormalizer()
        val a = normalizer.normalize("long-openai-style-id-with-pipes|1234567890")
        val b = normalizer.normalize("long-openai-style-id-with-pipes|1234567890")
        assertEquals(a, b)
        assertEquals(9, a.length)
        assertTrue(a.all { it.isLetterOrDigit() })

        val c = normalizer.normalize("another-long-openai-style-id|0987654321")
        assertTrue(c.length <= 9)
        // Distinct inputs never collapse onto the same normalized id.
        assertTrue(a != c || "long-openai-style-id-with-pipes|1234567890" == "another-long-openai-style-id|0987654321")
    }

    @Test
    fun `buildToolResultText mirrors pi placeholder wording`() {
        val f = MistralConversationsPayload::buildToolResultText
        assertEquals("found", f("found", false, true, false))
        assertEquals("[tool error] found", f(" found ", false, true, true))
        assertEquals(
            "found\n[tool image omitted: model does not support images]",
            f("found", true, false, false),
        )
        assertEquals("(see attached image)", f("", true, true, false))
        assertEquals("[tool error] (see attached image)", f("", true, true, true))
        assertEquals(
            "(image omitted: model does not support images)",
            f("", true, false, false),
        )
        assertEquals(
            "[tool error] (image omitted: model does not support images)",
            f("", true, false, true),
        )
        assertEquals("(no tool output)", f("", false, true, false))
        assertEquals("[tool error] (no tool output)", f("", false, true, true))
    }
}
